---
- hosts: database
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install package
      command: pip install PyMySQL

    - name: Configure MySQL
      get_url:
        url: https://raw.githubusercontent.com/ZGlydHl4/Projet_DevOps/master/src/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        mode: 0644

    - name: Download database scheme
      get_url:
        url: https://raw.githubusercontent.com/ZGlydHl4/Projet_DevOps/master/src/Cars.sql
        dest: /home/azureuser
        mode: 0644

    - name: Import MySQL database
      command: mysql -u root < /home/azureuser/Cars.sql
