---
- hosts: loadbalancer
  tasks:
    - name: Install haproxy
      apt:
        name: haproxy
        state: present

    - name: Download haproxy
      get_url:
        url: https://raw.githubusercontent.com/ZGlydHl4/Projet_DevOps/master/src/requirement.txt
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644

    - name: Start haproxy
      command: service haproxy start
