---
- hosts: loadbalancer

  vars:
    - src: https://raw.githubusercontent.com/ZGlydHl4/Projet_DevOps/master/src
    
  tasks:
    - name: Install haproxy
      apt:
        name: haproxy
        state: present
      become: true
     
    - name: Download haproxy
      shell: wget {{ src }}/
      become: true

    - name: Configure haproxy
      shell: cp /home/user/Desktop/haproxy.cfg /etc/haproxy/haproxy.cfg
      become: true
    
    - name: Restart haproxy
      shell: service haproxy restart
      become: true
