---
- hosts: webserver
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Download requirements.txt
      get_url:
        url: https://raw.githubusercontent.com/ZGlydHl4/Projet_DevOps/master/src/requirement.txt
        dest: /home/azureuser
        mode: 0644

    - name: Download requirements.txt
      get_url:
        url: https://raw.githubusercontent.com/ZGlydHl4/Projet_DevOps/master/src/Server.py
        dest: /home/azureuser
        mode: 0644

    - name: Install package
      command: pip install -r /home/azureuser/requirements.txt

    - name: Start the web application
      shell: uvicorn Server:app --reload --host "{{ ansible_default_ipv4.address }}" --port 80 >/dev/null 2>&1 &
      async: 10
      poll: 0
      args:
        chdir: /home/azureuser
