---
- hosts: loadbalancer

  vars:
    - repo: https://github.com/TheoM83/Cars_Credibility
    - password: toor
    
  tasks:
  
    - name: Install haproxy
      apt:
        name: haproxy
        state: present
      become: true
      vars:
        ansible_become_password: "{{ password }}"
     
    - name: Install git
      apt:
        name: git
        state: present
      become: true
      vars:
        ansible_become_password: "{{ password }}"
     
    - name: Clone Github project
      git:
        repo: "{{ repo }}"
        dest: /home/user/Desktop
        force: yes

    - name: Configure haproxy
      shell: cp /home/user/Desktop/haproxy.cfg /etc/haproxy/haproxy.cfg
      become: true
      vars:
        ansible_become_password: "{{ password }}"
    
    - name: Restart haproxy
      shell: service haproxy restart
      become: true
      vars:
        ansible_become_password: "{{ password }}"
